-- Migración 010: Completar catálogo de aerolíneas (curado desde legacy)
-- Objetivo: ampliar cobertura operativa sin insertar registros ruido/no-aerolínea.

INSERT INTO airlines (code, name, is_active, created_at) VALUES
('4C', 'LATAM Colombia', 1, NOW()),
('4M', 'LATAM Argentina', 1, NOW()),
('4O', 'Interjet', 1, NOW()),
('7M', 'MAYAir', 1, NOW()),
('9J', 'Dana Airlines', 1, NOW()),
('9N', 'Tropic Air', 1, NOW()),
('AA', 'American Airlines', 1, NOW()),
('AB', 'Air Berlin', 1, NOW()),
('AC', 'Air Canada', 1, NOW()),
('AF', 'Air France', 1, NOW()),
('AM', 'Aeroméxico', 1, NOW()),
('AR', 'Aerolíneas Argentinas', 1, NOW()),
('AS', 'Alaska Airlines', 1, NOW()),
('AV', 'Avianca', 1, NOW()),
('B6', 'JetBlue Airways', 1, NOW()),
('BA', 'British Airways', 1, NOW()),
('BV', 'Blue Panorama Airlines', 1, NOW()),
('CM', 'Copa Airlines', 1, NOW()),
('CU', 'Cubana de Aviación', 1, NOW()),
('DE', 'Condor', 1, NOW()),
('DL', 'Delta Air Lines', 1, NOW()),
('E9', 'Evelop Airlines', 1, NOW()),
('EB', 'Wamos Air / Pullmantur Air', 1, NOW()),
('EK', 'Emirates', 1, NOW()),
('EW', 'Eurowings', 1, NOW()),
('EY', 'Etihad Airways', 1, NOW()),
('F9', 'Frontier Airlines', 1, NOW()),
('G3', 'GOL Linhas Aéreas', 1, NOW()),
('G4', 'Allegiant Air', 1, NOW()),
('IB', 'Iberia', 1, NOW()),
('JJ', 'LATAM Brasil', 1, NOW()),
('JL', 'Japan Airlines', 1, NOW()),
('KL', 'KLM', 1, NOW()),
('KM', 'KM Malta Airlines', 1, NOW()),
('LA', 'LATAM Airlines', 1, NOW()),
('LH', 'Lufthansa', 1, NOW()),
('LP', 'LATAM Perú', 1, NOW()),
('LX', 'Swiss International Air Lines', 1, NOW()),
('MY', 'Maya Island Air', 1, NOW()),
('NH', 'ANA', 1, NOW()),
('NK', 'Spirit Airlines', 1, NOW()),
('NO', 'Neos', 1, NOW()),
('NZ', 'Air New Zealand', 1, NOW()),
('P5', 'Wingo', 1, NOW()),
('PZ', 'LATAM Paraguay', 1, NOW()),
('Q6', 'Skytrans', 1, NOW()),
('QF', 'Qantas', 1, NOW()),
('SE', 'XL Airways', 1, NOW()),
('SU', 'Aeroflot', 1, NOW()),
('SWG', 'Sunwing Airlines', 1, NOW()),
('SWQ', 'Swift Air', 1, NOW()),
('SY', 'Sun Country Airlines', 1, NOW()),
('TB', 'Jetairfly / TUI fly Belgium', 1, NOW()),
('TCX', 'Thomas Cook Airlines', 1, NOW()),
('TOM', 'TUI Airways', 1, NOW()),
('TS', 'Air Transat', 1, NOW()),
('UA', 'United Airlines', 1, NOW()),
('UN', 'Transaero', 1, NOW()),
('UX', 'Air Europa', 1, NOW()),
('VA', 'Virgin Australia', 1, NOW()),
('VB', 'VivaAerobus', 1, NOW()),
('VS', 'Virgin Atlantic', 1, NOW()),
('VW', 'Aeromar', 1, NOW()),
('VX', 'Virgin America', 1, NOW()),
('WK', 'Edelweiss Air', 1, NOW()),
('WN', 'Southwest Airlines', 1, NOW()),
('WS', 'WestJet', 1, NOW()),
('Y4', 'Volaris', 1, NOW())
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  is_active = VALUES(is_active);
