-- Migración 012: Catálogo de países (nuevo)
-- Nota: actualmente no hay módulo funcional que lo consuma, queda listo para futuras mejoras.

CREATE TABLE IF NOT EXISTS countries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  iso2 CHAR(2) NOT NULL,
  iso3 CHAR(3) NOT NULL,
  phone_code VARCHAR(10) NULL,
  name_en VARCHAR(120) NOT NULL,
  name_es VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  UNIQUE KEY uq_countries_iso2 (iso2),
  UNIQUE KEY uq_countries_iso3 (iso3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO countries (iso2, iso3, phone_code, name_en, name_es, is_active, created_at) VALUES
('MX', 'MEX', '52', 'Mexico', 'México', 1, NOW()),
('US', 'USA', '1', 'United States', 'Estados Unidos', 1, NOW()),
('CA', 'CAN', '1', 'Canada', 'Canadá', 1, NOW()),
('GB', 'GBR', '44', 'United Kingdom', 'Reino Unido', 1, NOW()),
('ES', 'ESP', '34', 'Spain', 'España', 1, NOW()),
('FR', 'FRA', '33', 'France', 'Francia', 1, NOW()),
('DE', 'DEU', '49', 'Germany', 'Alemania', 1, NOW()),
('IT', 'ITA', '39', 'Italy', 'Italia', 1, NOW()),
('NL', 'NLD', '31', 'Netherlands', 'Países Bajos', 1, NOW()),
('BE', 'BEL', '32', 'Belgium', 'Bélgica', 1, NOW()),
('CH', 'CHE', '41', 'Switzerland', 'Suiza', 1, NOW()),
('AT', 'AUT', '43', 'Austria', 'Austria', 1, NOW()),
('IE', 'IRL', '353', 'Ireland', 'Irlanda', 1, NOW()),
('PT', 'PRT', '351', 'Portugal', 'Portugal', 1, NOW()),
('SE', 'SWE', '46', 'Sweden', 'Suecia', 1, NOW()),
('NO', 'NOR', '47', 'Norway', 'Noruega', 1, NOW()),
('DK', 'DNK', '45', 'Denmark', 'Dinamarca', 1, NOW()),
('FI', 'FIN', '358', 'Finland', 'Finlandia', 1, NOW()),
('IS', 'ISL', '354', 'Iceland', 'Islandia', 1, NOW()),
('PL', 'POL', '48', 'Poland', 'Polonia', 1, NOW()),
('CZ', 'CZE', '420', 'Czechia', 'Chequia', 1, NOW()),
('HU', 'HUN', '36', 'Hungary', 'Hungría', 1, NOW()),
('RO', 'ROU', '40', 'Romania', 'Rumania', 1, NOW()),
('RU', 'RUS', '7', 'Russia', 'Rusia', 1, NOW()),
('TR', 'TUR', '90', 'Turkey', 'Turquía', 1, NOW()),
('BR', 'BRA', '55', 'Brazil', 'Brasil', 1, NOW()),
('AR', 'ARG', '54', 'Argentina', 'Argentina', 1, NOW()),
('CL', 'CHL', '56', 'Chile', 'Chile', 1, NOW()),
('CO', 'COL', '57', 'Colombia', 'Colombia', 1, NOW()),
('PE', 'PER', '51', 'Peru', 'Perú', 1, NOW()),
('EC', 'ECU', '593', 'Ecuador', 'Ecuador', 1, NOW()),
('VE', 'VEN', '58', 'Venezuela', 'Venezuela', 1, NOW()),
('UY', 'URY', '598', 'Uruguay', 'Uruguay', 1, NOW()),
('PY', 'PRY', '595', 'Paraguay', 'Paraguay', 1, NOW()),
('BO', 'BOL', '591', 'Bolivia', 'Bolivia', 1, NOW()),
('CR', 'CRI', '506', 'Costa Rica', 'Costa Rica', 1, NOW()),
('PA', 'PAN', '507', 'Panama', 'Panamá', 1, NOW()),
('GT', 'GTM', '502', 'Guatemala', 'Guatemala', 1, NOW()),
('SV', 'SLV', '503', 'El Salvador', 'El Salvador', 1, NOW()),
('HN', 'HND', '504', 'Honduras', 'Honduras', 1, NOW()),
('NI', 'NIC', '505', 'Nicaragua', 'Nicaragua', 1, NOW()),
('DO', 'DOM', '1', 'Dominican Republic', 'República Dominicana', 1, NOW()),
('CU', 'CUB', '53', 'Cuba', 'Cuba', 1, NOW()),
('JM', 'JAM', '1', 'Jamaica', 'Jamaica', 1, NOW()),
('BS', 'BHS', '1', 'Bahamas', 'Bahamas', 1, NOW()),
('AU', 'AUS', '61', 'Australia', 'Australia', 1, NOW()),
('NZ', 'NZL', '64', 'New Zealand', 'Nueva Zelanda', 1, NOW()),
('JP', 'JPN', '81', 'Japan', 'Japón', 1, NOW()),
('KR', 'KOR', '82', 'South Korea', 'Corea del Sur', 1, NOW()),
('CN', 'CHN', '86', 'China', 'China', 1, NOW()),
('IN', 'IND', '91', 'India', 'India', 1, NOW()),
('AE', 'ARE', '971', 'United Arab Emirates', 'Emiratos Árabes Unidos', 1, NOW()),
('SA', 'SAU', '966', 'Saudi Arabia', 'Arabia Saudita', 1, NOW()),
('IL', 'ISR', '972', 'Israel', 'Israel', 1, NOW()),
('ZA', 'ZAF', '27', 'South Africa', 'Sudáfrica', 1, NOW())
ON DUPLICATE KEY UPDATE
  phone_code = VALUES(phone_code),
  name_en = VALUES(name_en),
  name_es = VALUES(name_es),
  is_active = VALUES(is_active);
